name: called

on:
  workflow_call:
    # test的にinputsをあわせてみる
    inputs:
      migration-check:
        description: Migrationファイルの存在チェックを行うかどうか
        type: boolean
        required: true
      branch:
        description: デプロイ対象ブランチ
        type: string
        required: false
        default: ${{ github.ref_name }}
      target:
        description: デプロイ先環境
        type: string
        required: false
        default: ${{ github.ref_name }}

jobs:
  # inputsの値をログに出力
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "migration-check: ${{ inputs.migration-check }}"
          echo "branch: ${{ inputs.branch }}"
          echo "target: ${{ inputs.target }}"

  # Migrationファイルの存在チェック
  check-migration-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check add migration files
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            migration-check:
              - 'src/migration/**'
            migration-check-2:
              - 'src/migration/2/**'
    outputs:
      migration-check: ${{ steps.filter.outputs.migration-check }}
      migration-check-2: ${{ steps.filter.outputs.migration-check-2 }}

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
